# Generated by Django 2.1.7 on 2022-06-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_auto_20220625_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
