# Generated by Django 2.1.7 on 2022-06-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
